{% set name = "enfrosp_enmapboxapp" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/enfrosp_enmapboxapp-{{ version }}.tar.gz
  sha256: 9df28e86a8714d95852328bf073a2820c013f2a0c90f3d5652050f2db1d0abe3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - enfrosp >=0.1.2
    - packaging
    - psutil
    - qgis >=3.40.3

test:
  imports:
    - enfrosp_enmapboxapp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/enfrosp_enmapboxapp
  summary: A graphical user interface for EnFROSP as an add-in for the EnMAP-Box QGIS plugin
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
